name: CI for Angular
on: push
jobs:
  unit-test:
    runs-on: ubuntu-latest
    steps:
      - name: Clone Repo
        uses: actions/checkout@v2
      - name: Node Setup
        uses: actions/setup-node@v2
        with:
          node-version: 14.x
      - name: Install Dependencies
        run: npm ci
      - name: Run Tests
        # run: npx ng test --no-watch --code-coverage --browsers=ChromeHeadlessCI
        run: npm run test -- --no-watch --code-coverage --browsers=ChromeHeadlessCI
